-- Add comprehensive theme customization columns to restaurants table
ALTER TABLE public.restaurants 
ADD COLUMN IF NOT EXISTS text_color VARCHAR(50) DEFAULT '#FFFFFF',
ADD COLUMN IF NOT EXISTS card_color VARCHAR(50) DEFAULT '#1a1f2e',
ADD COLUMN IF NOT EXISTS card_text_color VARCHAR(50) DEFAULT '#FFFFFF',
ADD COLUMN IF NOT EXISTS price_color VARCHAR(50) DEFAULT '#FF8A4C',
ADD COLUMN IF NOT EXISTS category_header_color VARCHAR(50) DEFAULT '#FF8A4C',
ADD COLUMN IF NOT EXISTS header_gradient_start VARCHAR(50) DEFAULT '#000000',
ADD COLUMN IF NOT EXISTS header_gradient_end VARCHAR(50) DEFAULT '#1a1f2e',
ADD COLUMN IF NOT EXISTS button_color VARCHAR(50) DEFAULT '#FF8A4C',
ADD COLUMN IF NOT EXISTS button_text_color VARCHAR(50) DEFAULT '#FFFFFF',
ADD COLUMN IF NOT EXISTS border_color VARCHAR(50) DEFAULT '#2a3441',
ADD COLUMN IF NOT EXISTS font_family VARCHAR(100) DEFAULT 'Inter';